# Generated by Django 3.2.3 on 2021-06-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whitelist_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_address', models.CharField(max_length=100)),
                ('token_id', models.BigIntegerField()),
                ('whitelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nftbackend.whitelist')),
            ],
        ),
        migrations.CreateModel(
            name='Claimant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('has_claimed', models.BooleanField(default=False)),
                ('whitelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nftbackend.whitelist')),
            ],
        ),
    ]
