# Generated by Django 3.2.3 on 2021-06-19 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nftbackend', '0004_auto_20210608_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='whitelist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nftbackend.whitelist'),
        ),
    ]
