# Generated by Django 3.2.3 on 2021-06-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nftbackend', '0005_alter_nft_whitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='contract_type',
            field=models.CharField(choices=[('1155', 'ERC 1155'), ('721', 'ERC 721')], default='1155', max_length=4),
        ),
    ]
